### ISSUE TITLE
Bebedeira 13/08/2019

### ISSUE THREAD

**Issue by rafaelcamargo** [rafaelcamargo/remoteers#1]
O próximo momento oportuno para deliberações gerais sobre a vida, bebida e humanidade se aproxima. Sugestão de data: **13/08/2019**.

Quem vai?

@lucasfcunha 
@ericovis
@ftwasilewski
@diogotrentini
@andrebr
@gustavowt 
@thiagopradi

Usem as arrobas e chamem seus amigos!

**UPDATE**

**Local:** [Parque Opa](https://www.google.com/maps/uv?hl=en&pb=!1s0x94deb022cf9abe45%3A0xc42cfb190fe4dc12!2m22!2m2!1i80!2i80!3m1!2i20!16m16!1b1!2m2!1m1!1e1!2m2!1m1!1e3!2m2!1m1!1e5!2m2!1m1!1e4!2m2!1m1!1e6!3m1!7e115!4shttps%3A%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipPWn3ra1JOn4jlQQ0HFXMCU5B3tsguRYGyTMqkW%3Dw480-h320-k-no!5smax%20colin%20joinville%20parque%20opa%20-%20Google%20Search!15sCAQ&imagekey=!1e10!2sAF1QipPWn3ra1JOn4jlQQ0HFXMCU5B3tsguRYGyTMqkW&sa=X&ved=2ahUKEwj0-or-t-zjAhVuILkGHVQCCAkQoiowCnoECA8QBg)
**Horário:** 19h30

**Comment by lucasfcunha** [comment]
Mas isso não deveria ser um PR? Pra sugerir modificações ou aceitar caso posssa ir.

:trollface:

**Comment by rafaelcamargo** [comment]
@lucasfcunha Considerei o encontro como algo a ser resolvido ainda 😛

**Comment by andrebr** [comment]
@lucasfcunha virou um bot? 😂 

<img width="679" alt="Screen Shot 2019-08-05 at 3 52 33 PM" src="https://user-images.githubusercontent.com/385648/62487798-1d3e1d00-b799-11e9-903e-75b45b4ab42a.png">

**Comment by rafaelcamargo** [comment]
@lucasfcunha Tu que reclamou do Old a última vez. Qual é o lugar que lhe agrada senhor?

**Comment by lucasfcunha** [comment]
@andrebr nada mano, produtividade a mil.

Na verdade eu to com um site de resumo de noticias 100% automatizado e eu to usando o git por baixo. Então basicamente é um bot rodando no meu usuário do git sim. Preciso separar isso logo... Hahaha

**Comment by lucasfcunha** [comment]
> @lucasfcunha Tu que reclamou do Old a última vez. Qual é o lugar que lhe agrada senhor?

@rafaelcamargo a parada da Opa ali na Max Colin é legal. Que que vcs acham?

**Comment by rafaelcamargo** [comment]
@lucasfcunha O [Parque Opa](https://www.google.com/maps/uv?hl=en&pb=!1s0x94deb022cf9abe45%3A0xc42cfb190fe4dc12!2m22!2m2!1i80!2i80!3m1!2i20!16m16!1b1!2m2!1m1!1e1!2m2!1m1!1e3!2m2!1m1!1e5!2m2!1m1!1e4!2m2!1m1!1e6!3m1!7e115!4shttps%3A%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipPWn3ra1JOn4jlQQ0HFXMCU5B3tsguRYGyTMqkW%3Dw480-h320-k-no!5smax%20colin%20joinville%20parque%20opa%20-%20Google%20Search!15sCAQ&imagekey=!1e10!2sAF1QipPWn3ra1JOn4jlQQ0HFXMCU5B3tsguRYGyTMqkW&sa=X&ved=2ahUKEwj0-or-t-zjAhVuILkGHVQCCAkQoiowCnoECA8QBg) boto fé! O Garagem Opa não curto pq é mt fumaça de fritura...

**Comment by lucasfcunha** [comment]
@rafaelcamargo eu tava falando da Garagem mesmo, tem um hamburguer fenomenal ali.

**Comment by andrebr** [comment]
será que num lugar mais longe não dificultaria a adesão? maioria do pessoal tá ali do lado, na JobScore

**Comment by lucasfcunha** [comment]
Cara, eu acho que não. Max é perto ali do pessoal também. Mas tem que ver a opinião do resto.

**Comment by rafaelcamargo** [comment]
bem, já tem 3 confirmado...
taxa de conversão de 50%. o evento está se demonstrando promissor 🎉

**Comment by ftwasilewski** [comment]
I'm in.

**Comment by rafaelcamargo** [comment]
@lucasfcunha 

> eu tava falando da Garagem mesmo, tem um hamburguer fenomenal ali.

Lá no Parque Opa tem o boutique do frango. Já comi lá, é top.

**Comment by lucasfcunha** [comment]
@thiagopradi e @gustavowt bora?

**Comment by gustavowt** [comment]
Porra, parque opa nao, bora no Mad Dwarf entao

**Comment by rafaelcamargo** [comment]
> Porra, parque opa nao, bora no Mad Dwarf entao

humm... ostentação ein!

**Comment by gustavowt** [comment]
Tem chop do mesmo preço da opa se quiser, só paga caro se quiser

**Comment by lucasfcunha** [comment]
Ná po, tamo indo no Parque Opa por causa das opções de comida. Mad Dwarf tem nada de opção praticamente. Ostentação demais.

**Comment by rafaelcamargo** [comment]
Vamos fazer o poll:

**Parque Opa**
  - @rafaelcamargo 
  - @lucasfcunha

**Mad Dwarf**
  - @gustavowt 

Ponham seus nomezinho alí ☝️

**Comment by gustavowt** [comment]
> Ná po, tamo indo no Parque Opa por causa das opções de comida. Mad Dwarf tem nada de opção praticamente. Ostentação demais.

é doido? eles tem uns 4 tipos de hamburguer muito tops. Quando que tu foi la pra dizer isso?

**Comment by lucasfcunha** [comment]
> > Ná po, tamo indo no Parque Opa por causa das opções de comida. Mad Dwarf tem nada de opção praticamente. Ostentação demais.
> 
> é doido? eles tem uns 4 tipos de hamburguer muito tops. Quando que tu foi la pra dizer isso?

Sempre que eu fui lá era uma opção de hamburger, algum prato, um sanduba e deu.

**Comment by gustavowt** [comment]
> > > Ná po, tamo indo no Parque Opa por causa das opções de comida. Mad Dwarf tem nada de opção praticamente. Ostentação demais.
> > 
> > 
> > é doido? eles tem uns 4 tipos de hamburguer muito tops. Quando que tu foi la pra dizer isso?
> 
> Sempre que eu fui lá era uma opção de hamburger, algum prato, um sanduba e deu.

Precisa ir denovo entao :)

**Comment by ericovis** [comment]
esse repo é um fork desse aqui? https://github.com/kelseyhightower/nocode

**Comment by thiagopradi** [comment]
Vou estar viajando no dia 13, mas bom chopp galera! no próximo apareço!

**Comment by rafaelcamargo** [comment]
@ericovis 2.430 issues!!! 😂😂😂😂😂😂

**Comment by lucasfcunha** [comment]
Pronto @andrebr,

Movi meu bot https://github.com/astratu :D

**Comment by rafaelcamargo** [comment]
@lucasfcunha 👏 👏👏

Tudo certo pra amanhã cambada?

**Comment by gustavowt** [comment]
Mad Dwarf?

**Comment by rafaelcamargo** [comment]
@gustavowt Se for pra ir mais gente, por mim tá de boa! O que o resto da galera diz ae???!! Bóra?

**Comment by ftwasilewski** [comment]
Parquezinho né.

**Comment by ftwasilewski** [comment]
@wesklei

**Comment by gustavowt** [comment]
Caras, podem fazer onde voces quiserem, nao vou poder novamente.

**Comment by rafaelcamargo** [comment]
Então é isso galera. 19h30 no Parque Opa.
