### ISSUE TITLE
Bebedeira 01/10/2019 19h

### ISSUE THREAD

**Issue by rafaelcamargo** [rafaelcamargo/remoteers#2]
Está marcado o próximo evento para refletirmos sobre o clima, sobre programação e, claro, sobre a vida! Sugestão de data: **19/09/2019**.

Quem vai?

@lucasfcunha 
@ericovis
@ftwasilewski
@diogotrentini
@andrebr
@gustavowt 
@thiagopradi
@jonysk
@leandrorosa

**Local:** ?
**Horário:** 19h30

Usem as arrobas e chamem seus amiguinhos!

**Comment by andrebr** [comment]
E aeee! Pra mim ficaria melhor dia 17, terça-feira.

19/09/2019 às 19h foi por acaso? kkkkk

**Comment by andrebr** [comment]
@rafaelcamargo - add o @leandrorosa

**Comment by rafaelcamargo** [comment]
@andrebr Tu tá brincando que tu conhece o @leandrorosa?? Essa vida é só surpresa! haha

Tá adicionado!

> E aeee! Pra mim ficaria melhor dia 17, terça-feira.

Pô, o problema é que esse é o dia do aniversário do meu filho e daí eu vou pro Beto Carreiro porque daí ele não paga (mentira!!! haha). Mas que é o dia do aniversário dele é verdade. Então, já to comprometido aqui com um programa de família. Mas se não rolar no dia 19 pra geral, a gente pode marcar pra outro dia também... no stress.

O que dizem o resto aí seus marmanjos?

**Comment by rafaelcamargo** [comment]
@andrebr @lucasfcunha Terça (01/10) às 19h rola? Pra mim tá show e pode ser no Old, sugiram lugares!!

**Comment by andrebr** [comment]
@rafaelcamargo bora!

Old facilita pro pessoal da JobScore, que tá ali do lado.
Se estiverem enjoados dali, Opa é uma boa.
Mas se o dinheiro no colchão estiver atrapalhando o sono, Madero resolve.

**Comment by rafaelcamargo** [comment]
> Mas se o dinheiro no colchão estiver atrapalhando o sono, Madero resolve.

🤣🤣🤣🤣

Acho que a cerveja no old é mais interessante. Mas os dois lugares são de boa pra mim ✌️

**Comment by ftwasilewski** [comment]
bora

**Comment by ftwasilewski** [comment]
@tiaagosr

**Comment by rafaelcamargo** [comment]
já que *three is a crowd*, tá fechado! old às 19h ✌️

**Comment by ftwasilewski** [comment]
@wesklei @ericovis

**Comment by thiagopradi** [comment]
Não consigo ir hoje - mas agradeço o convite galera! Qualquer hora apareço no Old para tomar uma com vocês! Abraço!

**Comment by tiaagosr** [comment]
Caramba, vi a pouco apenas hahaha. Olharei os emails do github com mais carinho a partir de agora :P
